# Generated by Django 5.2.3 on 2025-06-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='plate',
            field=models.IntegerField(blank=True, max_length=0, null=True),
        ),
    ]
